name: nutrisoft-test

on:
  pull_request:
    types:
      - closed
    # branches:
    #   - kakuyo
    #   - miguel

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: db_nutrisoft
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: lema50411
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJSON(github) }}
      #   run: echo "$GITHUB_CONTEXT"
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Whoami
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.EC2_HOST_MIGUEL }}
      #     username: ${{ secrets.EC2_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: whoami

      # - name: Whoami
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.EC2_HOST_KAKUYO }}
      #     username: ${{ secrets.EC2_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: whoami
        
      - name: Test EC2 (for miguel branch)
        if: github.event.pull_request.base.ref == 'miguel'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_MIGUEL }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            touch /home/ubuntu/miguel.txt

      - name: Test EC2 (for kakuyo branch)
        if: github.event.pull_request.base.ref == 'kakuyo'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_KAKUYO }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            touch /home/ubuntu/master.txt

      - name: Set up Django
        run: |
          python manage.py makemigrations
          python manage.py migrate
          python manage.py runserver &
        
      - name: Stop Django server
        run: |
          kill $(lsof -t -i:8000)
