# Generated by Django 4.0 on 2022-04-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
