# Generated by Django 4.0 on 2022-04-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_pacientes_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
